channels:
- conda-forge
dependencies:
- autodocsumm
- click
- enstat
- goosehdf5 >=0.23.0
- goosempl
- gooseslurm
- h5glance
- h5py
- mv_regex
- numpy
- parallel
- pdfcombine
- pre-commit
- python
- python-cppcolormap
- scikit-image
- setuptools_scm
- shelephant
- tqdm
