channels:
- conda-forge
dependencies:
- autodocsumm
- click
- enstat >=0.9.6
- goosehdf5 >=0.23.0
- goosempl
- gooseslurm
- h5glance
- h5py
- mv_regex
- numpy
- parallel
- pdfcombine
- pre-commit
- python
- python-cppcolormap
- python-gooseeye >=0.7.1
- setuptools_scm
- shelephant
- tqdm
