channels:
- conda-forge
dependencies:
- autodocsumm
- click
- enstat >=0.9.6
- furo
- goosehdf5 >=0.26.1
- goosempl
- gooseslurm
- h5glance
- h5py
- mv_regex
- numpy
- parallel
- pdfcombine
- pre-commit
- pytest
- python >=3.10
- python-cppcolormap
- python-gooseepm >=0.10.0
- python-gooseeye >=0.8.0
- setuptools_scm
- shelephant
- sphinx
- sphinx-argparse
- tqdm
