[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]

[project]
authors = [{name = "Tom de Geus", email = "tom@geus.me"}]
classifiers = ["License :: OSI Approved :: MIT License"]
dependencies = [
  "enstat",
  "GooseEPM >=0.5.2",
  "GooseHDF5 >=0.23.0",
  "h5py",
  "numpy",
  "tqdm"
]
description = "Simple dataset management"
dynamic = ["version"]
name = "mycode_thermal_epm"
readme = "README.md"
requires-python = ">=3.7"

[project.scripts]
AthermalPreparation_Generate = "mycode_thermal_epm.AthermalPreparation:Generate"
AthermalPreparation_Run = "mycode_thermal_epm.AthermalPreparation:Run"
AthermalQuasiStatic_BranchPreparation = "mycode_thermal_epm.AthermalQuasiStatic:BranchPreparation"
AthermalQuasiStatic_EnsembleInfo = "mycode_thermal_epm.AthermalQuasiStatic:EnsembleInfo"
AthermalQuasiStatic_Plot = "mycode_thermal_epm.AthermalQuasiStatic:Plot"
AthermalQuasiStatic_Run = "mycode_thermal_epm.AthermalQuasiStatic:Run"
ExtremeValue_BranchPreparation = "mycode_thermal_epm.ExtremeValue:BranchPreparation"
ExtremeValue_EnsembleInfo = "mycode_thermal_epm.ExtremeValue:EnsembleInfo"
ExtremeValue_Plot = "mycode_thermal_epm.ExtremeValue:Plot"
ExtremeValue_Run = "mycode_thermal_epm.ExtremeValue:Run"
ExtremeValue_RunAvalache = "mycode_thermal_epm.ExtremeValue:RunAvalache"
Thermal_BranchPreparation = "mycode_thermal_epm.Thermal:BranchPreparation"
Thermal_EnsembleInfo = "mycode_thermal_epm.Thermal:EnsembleInfo"
Thermal_Plot = "mycode_thermal_epm.Thermal:Plot"
Thermal_Run = "mycode_thermal_epm.Thermal:Run"
Thermal_UpgradeData = "mycode_thermal_epm.Thermal:UpgradeData"

[project.urls]
Source = "https://github.com/tdegeus/mycode_thermal_epm"

[tool.setuptools_scm]
write_to = "mycode_thermal_epm/_version.py"
